# Server
server.port=8080

# Stockfish
stockfish.path=stockfish/stockfish/stockfish-windows-x86-64-avx2.exe
stockfish.hash=128
stockfish.threads=1
stockfish.pool-size=4
stockfish.default-depth=15

# CORS
app.cors.allowed-origins=http://localhost:3000

# Logging
logging.level.com.chess.engine=DEBUG
spring.mvc.async.request-timeout=-1
